apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-api
  namespace: app-vote
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: https://github.com/mikimoyal/vote-api.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
